// <auto-generated />
using System;
using HelloEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelloEF.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240719201721_ManyToManyRelationship")]
    partial class ManyToManyRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HelloEF.Owner", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Owner");
                });

            modelBuilder.Entity("HelloEF.Pet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long?>("chaos")
                        .HasColumnType("bigint");

                    b.Property<int?>("cuteness")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("species")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("OwnerPet", b =>
                {
                    b.Property<int>("Ownersid")
                        .HasColumnType("int");

                    b.Property<int>("Petsid")
                        .HasColumnType("int");

                    b.HasKey("Ownersid", "Petsid");

                    b.HasIndex("Petsid");

                    b.ToTable("OwnerPet");
                });

            modelBuilder.Entity("OwnerPet", b =>
                {
                    b.HasOne("HelloEF.Owner", null)
                        .WithMany()
                        .HasForeignKey("Ownersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelloEF.Pet", null)
                        .WithMany()
                        .HasForeignKey("Petsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
